mobile_base_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'left_wheel_joint'
  right_wheel : 'right_wheel_joint'
  publish_rate: 50.0  
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.3068 # meters 
  wheel_radius : 0.075    # meters

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.25

  # Base frame_id
  base_frame_id: base_footprint #default: base_link

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.5
      min_velocity           : -0.5 
      has_acceleration_limits: true
      max_acceleration       : 0.5 
      min_acceleration       : -0.5 
      has_jerk_limits        : true
      max_jerk               : 0.2 
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 0.5 #1.7  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 0.2  # rad/s^2
      has_jerk_limits        : true
      max_jerk               : 0.2  # rad/s^3

  #Publish to TF directly or not
  enable_odom_tf: true

  #Name of frame to publish odometry in
  odom_frame_id: odom

  # Publish the velocity command to be executed. 
  # It is to monitor the effect of limiters on the controller input.
  publish_cmd: true
