local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  max_obstacle_height: 1.5
  width: 2.5
  height: 2.5
  resolution: 0.03
  transform_tolerance: 0.5
  inflation_radius: 0.55
  cost_scaling_factor: 5.0
  

